### ISSUE TITLE
Helper not found

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/quiz#3]
ON2AT tested the module with Xoops 2.5.10 and got this error on installation:
Error: Class 'XoopsModules\Quiz\Helper' not found

**Comment by mambax7** [comment]
To be honest, I don't test anymore with XOOPS 2.5.10, as I'm focused on moving all modules to XOOPS 2.5.11 and PHP 7.4+, with the focus on PHP 8+ 
Please ask him to test on XOOPS 2.5.11 Beta 2

**Comment by mambax7** [comment]
@cesagonchu On XOOPS 2.5.11 Beta 2 and PHP 8.2 Beta, it installs just fine:
![image](https://user-images.githubusercontent.com/613686/185939760-f9cf7a0d-e788-4fa4-a81d-ec20e0495bbc.png)

**Comment by mambax7** [comment]
I've made some updates and released it as Beta 2: https://github.com/mambax7/quiz/releases/tag/2.00_Beta-2

Please test it on XOOPS 2.5.11 Beta 2 and let me know if you find any issues.
