### ISSUE TITLE
Unknown: trim():

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/quiz#4]
On admin side I get this error:
Unknown: trim(): Passing null to parameter #1 ($string) of type string is deprecated in file /class/libraries/vendor/symfony/yaml/Inline.php line 49

___
My config

Quiz 2.0 Beta2 (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.30-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
Same as in MyAlbum issue: https://github.com/mambax7/myalbum/issues/7
