### ISSUE TITLE
db:system_notification_select.html

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/quiz#6]
When I go to user  side and after creating a quiz on admin, I get this error:
Warning: Smarty error: unable to read resource: "db:system_notification_select.html" in file /class/smarty/Smarty.class.php line 1102

___

My config

Quiz 2.0 Beta2 (english version)
Xoops 2.5.11-Beta2 (english version)
PHP 8.1.2
MYSQL 8.0.30-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
That's an issue with the System module  and not with Quiz
